const Data = [
  {
    id: 1,
    position: "Manager of Mobility Services Data",
    company: "Central Florida Regional Transportation Authority (LYNX)",
    location: "Orlando, FL",
    dates: "10/2021 – Current",
    responsibilities: [
      "Manage cross-functional projects using advanced data monitoring and analysis techniques for strategic decision-making and operational performance improvement.",
      "Ensure compliance with ADA and other regulations through audits and operations data analysis.",
      "Develop reporting criteria and monitored service delivery and performance.",
      "Resolve service issues by recommending operational efficiency solutions.",
      "Manage operating and capital budgets.",
      "Provides data analysis and support to prepare the AOR (Annual Operating Report) and NTD (National Transit Database) reports.",
    ],
  },
  {
    id: 2,
    position: "Executive Director of Operations",
    company: "Trans Voyage Taxi",
    location: "Aurora, CO",
    dates: "08/2018 - Current",
    responsibilities: [
      "Devised, deployed and monitored processes to boost long-term business success and increase profit levels 23%.",
      "Developed and implemented business processes.",
      "Cultivated and strengthened lasting client relationships using account management.",
      "Created, managed and executed business plan and communicated company vision and objectives to motivate teams.",
      "Directed HR operations, including strategic workforce planning, goal cascading, performance management, staffing and benefits administration.",
      "Managed purchasing, sales, marketing and customer account operations efficiently.",
      "Led company to successful product launch and growth by developing initial product roadmap and go-to-market strategy.",
      "Enhanced operational efficiency and productivity by managing budgets and accounts.",
      "Reduced operational risks while organizing safety classes and customer service classes. As a result, reduced the number of accidents to 1 accident for the year of 2020 and only 2 accidents in 2019.",
      "Tracked employee attendance and punctuality, addressing repeat problems quickly to prevent long-term habits.",
      "Recruited, hired and trained initial personnel, working to establish key internal functions and outline scope of positions for new organization.",
      "Observed each employee's individual strengths and initiated mentoring program to improve areas of weakness.",
      "Established and administered annual budget with effective controls to prevent overages, minimize burn rate and support sustainability objectives.",
      "Upheld great standards of leadership for employees, consistently leading by example for best-in-class.",
      "Measuring industry trends to set proper measurements for competition. Through business intelligence tools and skills, I was able to compete with the largest companies within the state of Colorado.",
      "Improved brand awareness by monitoring all marketing campaigns and fostering membership acquisitions and business development.",
      "Drove year-over-year business growth while leading operations, strategic vision and long-range planning.",
      "Reduced financial inconsistencies while assessing and verifying billing invoices and expense reports.",
      "Applied performance data to evaluate and improve operations, target current business conditions and forecast needs.",
      "Enhanced and redefined organizational structure to maintain company's competitive edge across territories.",
      "Designed modern employee recognition program which boosted productivity and improved morale.",
      "Chaired weekly meetings with executive leadership to identify opportunities for improvement, establish milestones and tailor products to individual markets.",
      "Supported top-level decision-making and strategy planning, forging productive relationships with top leaders and serving as key advocate for various personnel issues.",
      "Reduced budgetary expenditures by effectively negotiating contracts for more advantageous terms.",
      "Fostered work culture of collaboration and inclusion to increase morale and reduce turnover.",
      "Exercised appropriate cost control to meet budget restrictions and maximize profitability.",
      "Achieved regulatory compliance with no adverse audit findings for facilities, documentation compliance or safety.",
    ],
  },
  {
    id: 3,
    position: "Talent Acquisition Manager",
    company: "Metro Transportation Planning And Solutions Group",
    location: "Denver, CO",
    dates: "04/2017 - 05/2018",
    responsibilities: [
      "Developed communication and marketing plan and leveraged talent acquisition tools, resources and campaigns to source and attract top talent.",
      "Sourced and screened candidates for managerial roles and worked with hiring managers to coordinate interviews, offers and onboarding.",
      "Promoted increased focus on internal talent mobility and emerging talent across organization.",
      "Identified and created recruitment and administrative performance metrics and data to analyze trends, drive change and assess progress.",
      "Leveraged employee referrals, direct sourcing, Internet applications and recruitment agencies to source candidates for positions.",
      "Acted as brand ambassador to educate candidates on culture, career growth, benefits and advantages of working for company.",
      "Created onboarding solutions to tailor options for independent contractors hiring needs.",
      "Reviewed employment applications and background check reports to facilitate hiring process.",
      "Conducted compensation conversations with human resources and hiring managers to foster internal and external equity.",
      "Optimized sourcing networks and used proactive methods to direct source candidates.",
      "Evaluated resumes, interviewed and presented qualified candidates to hiring managers and solicited feedback to refine recruiting strategy.",
      "Partnered with the Company's COO to create effective talent acquisition training materials that supported culture and performance objectives.",
      "Created and drove talent acquisition and job placement strategies to attract diverse candidates.",
    ],
  },
  {
    id: 4,
    position: "General Manager",
    company: "Green Taxi Cooperative",
    location: "Denver, CO",
    dates: "03/2016 - 04/2017",
    responsibilities: [
      "Helped starting up the company along the side with its departments and employment needs.",
      "Applied performance data to evaluate and improve operations, target current business conditions and forecast needs.",
      "Developed value-added solutions and approaches by leveraging trends in customer marketplaces and industries.",
      "Delivered business strategy and developed systems and procedures to improve operational quality and team efficiency.",
      "Organized budgets, oversaw P&Ls and achieved margin targets consistently to stay on track with growth plans.",
      "Devised and deployed successful marketing strategies, dramatically boosting store ranking.",
      "Supported regulatory compliance by overseeing all audits to verify protocol adherence.",
      "Created, managed and executed business plan and communicated company vision and objectives to motivate teams.",
      "Boosted productivity by consolidating material planning, data collecting, payroll and accounting programs into one main system.",
      "Identified and capitalized on community business opportunities with effective networking.",
      "Enforced quality assurance protocols to deliver ideal customer experiences.",
      "Reviewed performance data to monitor and measure productivity, goal progress and activity levels.",
      "Created employee handbook and a driver manual.",
      "Developed effective business plans to align strategic decisions with long-term objectives.",
      "Improved brand awareness by monitoring all marketing campaigns and fostering membership acquisitions and business development.",
    ],
  },
  {
    id: 5,
    position: "General Manager",
    company: "Mile High Cab, Inc",
    location: "Denver, CO",
    dates: "02/2014 - 03/2016",
    responsibilities: [
      "Applied performance data to evaluate and improve operations, target current business conditions and forecast needs.",
      "Delivered business strategy and developed systems and procedures to improve operational quality and team efficiency.",
      "Developed value-added solutions and approaches by leveraging trends in customer marketplaces and industries.",
      "Organized budgets, oversaw P&Ls and achieved margin targets consistently to stay on track with growth plans.",
      "Boosted productivity by consolidating material planning, data collecting, payroll and accounting programs into one main system.",
      "Reduced corporate risk by managing shrink processes and controlling inventory levels.",
      "Managed budget implementations, employee reviews, training, schedules and contract negotiations.",
      "Reviewed performance data to monitor and measure productivity, goal progress and activity levels.",
      "Enforced quality assurance protocols to deliver ideal customer experiences.",
    ],
  },
  {
    id: 6,
    position: "General Store Manager",
    company: "Ralston Convenience Store",
    location: "Arvada, CO",
    dates: "08/2012 - 07/2014",
    responsibilities: [
      "Coordinated weekly conferences with store associates to communicate sales and customer service goals.",
      "Reviewed performance data to monitor and measure productivity, goal progress and activity levels.",
      "Set, enforced and optimized internal policies to maintain efficiency and responsiveness to demands.",
      "Set effective store schedules based on forecasted customer levels, individual employee knowledge and service requirements.",
      "Promoted team collaboration, performance and efficiency by fostering healthy environments focused on mutual success.",
      "Applied performance data to evaluate and improve operations, target current business conditions and forecast needs.",
      "Evaluated suppliers by assessing quality, timeliness and compliance of deliveries to maintain tight cost controls and maximize business operational efficiency.",
      "Addressed and resolved strategy issues to support sales management and guide business direction.",
      "Achieved consistent budget targets with optimal expense controls and elimination of unnecessary waste.",
      "Rotated merchandise and displays to feature new products and promotions.",
      "Established and administered annual budget with effective controls to prevent overages, minimize burn rate and support sustainability objectives.",
      "Analyzed and interpreted store trends with QuickBooks to facilitate planning.",
      "Developed new store location from ground up by hiring and training efficient team.",
      "Provided excellent customer service, promoting membership loyalty and increasing customer satisfaction rates.",
      "Minimized on-site cash with frequent deposits and high accuracy in predicting operations.",
      "Supervised and effectively trained 32 employees to decrease process lags and boost productivity.",
      "Managed weekly inventory transactions by creating templates to track optimal food and beverage stock.",
      "Promoted business strategy by implementing improvements based on guest feedback.",
      "Protected store from loss or theft by setting and enforcing clear security policies.",
    ],
  },
];

export default Data;
